{
 "title": "VMware -  Datastores",
 "description": "VMware - Datastores",
 "tags": [
  "prometheus",
  "vmware",
  "esxi"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "esxhostname",
    "label": "esxhostname",
    "query": {
     "query": "label_values(vsphere_host_cpu_usage_average,esxhostname)"
    }
   },
   {
    "name": "datastore",
    "label": "datastore",
    "query": {
     "query": "label_values(vsphere_datastore_disk_capacity_latest,dsname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Datastore usage  (%)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(30,((vsphere_datastore_disk_used_latest{dsname=~\"$datastore\"}) / vsphere_datastore_disk_capacity_latest{dsname=~\"$datastore\"}))",
     "legendFormat": "{{ dsname }}"
    }
   ]
  },
  {
   "title": "Datastore provisioned  (%)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(30,((vsphere_datastore_disk_provisioned_latest{dsname=~\"$datastore\"}) / vsphere_datastore_disk_capacity_latest{dsname=~\"$datastore\"}))",
     "legendFormat": "{{ dsname }}"
    }
   ]
  },
  {
   "title": "Disk read latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vsphere_host_disk_totalReadLatency_average{esxhostname=~\"$esxhostname\"}",
     "legendFormat": "{{ disk }}"
    }
   ]
  },
  {
   "title": "Disk write latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vsphere_host_disk_totalWriteLatency_average{esxhostname=~\"$esxhostname\"}",
     "legendFormat": "{{ disk }}"
    }
   ]
  },
  {
   "title": "$datastore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "datastore",
   "targets": [
    {}
   ]
  },
  {
   "title": "Capacity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vsphere_datastore_disk_capacity_latest{dsname=~\"$datastore\"}-vsphere_datastore_disk_used_latest{dsname=~\"$datastore\"})",
     "legendFormat": "Free Capacity"
    },
    {
     "expr": "vsphere_datastore_disk_capacity_latest{dsname=~\"$datastore\"}",
     "legendFormat": "Total Capacity"
    }
   ]
  },
  {
   "title": "Total R/W",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vsphere_datastore_datastore_numberReadAveraged_average{source=~\"$datastore\"}",
     "legendFormat": "Total Reads"
    },
    {
     "expr": "vsphere_datastore_datastore_numberWriteAveraged_average{source=~\"$datastore\"}",
     "legendFormat": "Total Write"
    }
   ]
  },
  {
   "title": "Capacity Summary",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vsphere_datastore_disk_used_latest{dsname=~\"$datastore\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "vsphere_datastore_disk_capacity_latest{dsname=~\"$datastore\"}-vsphere_datastore_disk_used_latest{dsname=~\"$datastore\"}",
     "legendFormat": "Free"
    }
   ]
  }
 ]
}