{
 "title": "VMware ESXi",
 "description": "VMware ESXi single instance graphs.",
 "tags": [
  "prometheus",
  "vmware",
  "esxi"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "esxhost",
    "label": "esxhost",
    "query": {
     "query": "label_values(vmware_host_boot_timestamp_seconds,host_name)"
    }
   },
   {
    "name": "datastore",
    "label": "datastore",
    "query": {
     "query": "label_values(vmware_datastore_capacity_size,ds_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DS $datastore usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "repeat": "datasource",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100*(1 - vmware_datastore_freespace_size{ds_name=~\"$datastore\"} / vmware_datastore_capacity_size{ds_name=~\"$datastore\"})",
     "legendFormat": "{{ ds_name }}"
    }
   ]
  },
  {
   "title": "$datastore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "datastore",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Capacity",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vmware_datastore_freespace_size{ds_name=~\"$datastore\"}/1024/1024/1024",
       "legendFormat": "Free Capacity"
      },
      {
       "expr": "vmware_datastore_capacity_size{ds_name=~\"$datastore\"}/1024/1024/1024",
       "legendFormat": "Total Capacity"
      }
     ]
    },
    {
     "title": "Capacity Summary",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(vmware_datastore_capacity_size{ds_name=~\"$datastore\"}-vmware_datastore_freespace_size\r\n{ds_name=~\"$datastore\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "vmware_datastore_freespace_size{ds_name=~\"$datastore\"}",
       "legendFormat": "Free"
      }
     ]
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ESXi host uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vmware_host_boot_timestamp_seconds{host_name=~\"$esxhost\"} / 32)"
    }
   ]
  },
  {
   "title": "Host Memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((vmware_host_memory_usage{host_name=~\"$esxhost\"}) * 100 / (vmware_host_memory_max{host_name=~\"$esxhost\"}))"
    }
   ]
  },
  {
   "title": "Host CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((vmware_host_cpu_usage{host_name=~\"$esxhost\"}) * 100 / (vmware_host_cpu_max{host_name=~\"$esxhost\"}))"
    }
   ]
  },
  {
   "title": "Host Memory ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmware_host_memory_max{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "Host Memory Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmware_host_memory_usage{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "Host Memory Free",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmware_host_memory_max{host_name=~\"$esxhost\"} - vmware_host_memory_usage{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "Number of VMs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_vm_power_state{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "Number of active VMs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_vm_power_state{host_name=~\"$esxhost\"} == 1) "
    }
   ]
  },
  {
   "title": "Number of powered off VMs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_vm_power_state{host_name=~\"$esxhost\"} == 0)"
    }
   ]
  },
  {
   "title": "List of powered off VMs",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 20 },
   "targets": [
    {
     "expr": "vmware_vm_power_state{host_name=~\"$esxhost\"} == 0",
     "legendFormat": "{{ vm_name }}"
    }
   ]
  },
  {
   "title": "vm Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "vmware_vm_mem_active_average{host_name=~\"$esxhost\"}",
     "legendFormat": "{{ vm_name }}"
    }
   ]
  },
  {
   "title": "vm CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "vmware_vm_cpu_usage_average{host_name=~\"$esxhost\"}",
     "legendFormat": "{{ vm_name }}"
    }
   ]
  },
  {
   "title": "VM unused memory ",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(30,(vmware_vm_memory_max{host_name=~\"$esxhost\"} - (vmware_vm_mem_active_average{host_name=~\"$esxhost\"} / 1024)))",
     "legendFormat": "{{ vm_name }}"
    }
   ]
  },
  {
   "title": "VM unused memory  (%)",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(30,(1 - (vmware_vm_mem_active_average{host_name=~\"$esxhost\"} / 1024) / vmware_vm_memory_max{host_name=~\"$esxhost\"}))",
     "legendFormat": "{{ vm_name }}"
    }
   ]
  }
 ]
}